import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>ZAS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="Keywords" content="nextjs, personal blog, blog " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <script src="/sc.js" strategy="lazyOnload"></script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to ZAS Blog</h1>
        <div className={styles.imagewrap}>
          <img
            className={styles.myimg}
            src="/homeimg.avif"
            width={237}
            height={158}
            alt="coder"
          />
        </div>
        <p className={styles.description}>
          A blog for students by a Best teacher
        </p>
        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="BlogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the language</p>
          </div>
          <div className="BlogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the language</p>
          </div>
          <div className="BlogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the language</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
